/**
 * Atlas Classifier — Step 4 of the V2 paste pipeline.
 *
 * Maps analyzer output (event_type + title + description + artifacts +
 * stack + capabilities) to Atlas v0.4 role IDs with confidence + reasoning,
 * via a single Anthropic API call using strict tool_use.
 *
 * Versioning is deterministic: the prompt is hand-baked into a versioned
 * file (`prompts/<version>.md`) generated by `scripts/generate-classifier-
 * prompt.ts`. When Atlas bumps, bump the constants here in lockstep with a
 * new prompt file. Receipts persist `classifier_version` so the graph can
 * be re-classified deterministically.
 *
 * Reference: docs/v2/STEP_4_ATLAS_CLASSIFIER_SPEC.md
 */

import Anthropic from '@anthropic-ai/sdk';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import type { Artifact, EventType, StackElement } from '@/schemas/proof-receipt-v0.1';

export const CLASSIFIER_VERSION = 'claude-classifier-v0.1.0';
const PROMPT_FILE = 'v0.1.0.md';
/**
 * Model selection: claude-sonnet-4-6.
 *
 * Calibrated for the classifier task: structured tool_use output, mid-
 * complexity reasoning, /paste/review latency budget. Confidence span on
 * the three locked fixtures (0.32 / 0.35 / 0.92) shows healthy calibration
 * without systematic over- or under-claiming. Cost matters at volume.
 *
 * Spec originally suggested claude-sonnet-4-7 with fallback to 4-6, but
 * sonnet-4-7 is not in the SDK model catalog as of 2026-05-15. Revisit if
 * production shows systematic miscalibration, or when 4-7 becomes available.
 */
const MODEL: Anthropic.Messages.MessageCreateParamsNonStreaming['model'] = 'claude-sonnet-4-6';
const MAX_TOKENS = 8192;
const MAX_ROLES = 5;
const MAX_REASONING_CHARS = 400;

const TOOL_NAME = 'classify_atlas_roles';
const TOOL_DEFINITION: Anthropic.Messages.Tool = {
  name: TOOL_NAME,
  description: 'Classify a proof of work into ShipStacked Atlas roles.',
  input_schema: {
    type: 'object',
    properties: {
      roles: {
        type: 'array',
        items: { type: 'string' },
        description: `Atlas v0.4 role IDs (e.g. A1, F3, G1). Max ${MAX_ROLES}.`,
      },
      confidence: {
        type: 'number',
        description: 'Confidence in the strongest role match. Between 0.0 and 1.0.',
      },
      reasoning: {
        type: 'string',
        description: `Short explanation shown to the user. Less than ${MAX_REASONING_CHARS} characters.`,
      },
    },
    required: ['roles', 'confidence', 'reasoning'],
  },
};

export interface AtlasClassifierInput {
  event_type: EventType;
  title: string;
  description: string;
  artifacts: Artifact[];
  stack: StackElement[];
  capabilities: string[];
}

export interface AtlasClassifierResult {
  inferred: string[];
  confidence: number;
  reasoning: string;
  classifier_version: string;
}

/**
 * Load system prompt once at module init and parse the valid role IDs out
 * of it so we can filter hallucinated outputs without a runtime DB query.
 */
function loadPrompt(): { systemPrompt: string; validRoleIds: Set<string> } {
  const promptPath = join(
    process.cwd(),
    'src/services/atlas-classifier/prompts',
    PROMPT_FILE
  );
  const systemPrompt = readFileSync(promptPath, 'utf-8');
  const validRoleIds = new Set<string>();
  for (const m of systemPrompt.matchAll(/^- \*\*([A-G]\d+)\*\*/gm)) {
    validRoleIds.add(m[1]);
  }
  if (validRoleIds.size === 0) {
    throw new Error(`No role IDs parsed out of ${promptPath} — prompt file shape changed?`);
  }
  return { systemPrompt, validRoleIds };
}

const { systemPrompt: SYSTEM_PROMPT, validRoleIds: VALID_ROLE_IDS } = loadPrompt();

const client = new Anthropic();

function formatUserMessage(input: AtlasClassifierInput): string {
  const lines: string[] = [];
  lines.push(`Event type: ${input.event_type}`);
  lines.push(`Title: ${input.title}`);
  lines.push(`Description: ${input.description}`);
  if (input.stack.length > 0) {
    lines.push(
      `Stack: ${input.stack
        .map((s) => `${s.name}${s.version ? ` ${s.version}` : ''} (${s.role})`)
        .join(', ')}`
    );
  } else {
    lines.push('Stack: (none reported)');
  }
  lines.push(
    `Capabilities: ${input.capabilities.length > 0 ? input.capabilities.join(', ') : '(none reported)'}`
  );
  if (input.artifacts.length > 0) {
    lines.push('Artifacts:');
    for (const a of input.artifacts) {
      const title = a.title ? ` — ${a.title}` : '';
      lines.push(`- ${a.kind}: ${a.url}${title}`);
    }
  }
  return lines.join('\n');
}

interface ToolInput {
  roles?: unknown;
  confidence?: unknown;
  reasoning?: unknown;
}

function findToolUseBlock(
  content: Anthropic.Messages.ContentBlock[]
): Anthropic.Messages.ToolUseBlock | null {
  for (const block of content) {
    if (block.type === 'tool_use' && block.name === TOOL_NAME) return block;
  }
  return null;
}

function validateAndShape(toolInput: ToolInput, warnings: string[]): AtlasClassifierResult {
  // roles
  let roles: string[] = [];
  if (Array.isArray(toolInput.roles)) {
    roles = toolInput.roles.filter((r): r is string => typeof r === 'string');
  }
  const filtered: string[] = [];
  for (const r of roles) {
    if (VALID_ROLE_IDS.has(r)) {
      if (!filtered.includes(r)) filtered.push(r);
    } else {
      warnings.push(`dropped unknown role id "${r}"`);
    }
  }
  const inferred = filtered.slice(0, MAX_ROLES);
  if (filtered.length > MAX_ROLES) {
    warnings.push(`truncated roles array from ${filtered.length} to ${MAX_ROLES}`);
  }

  // confidence
  let confidence = 0;
  if (typeof toolInput.confidence === 'number' && Number.isFinite(toolInput.confidence)) {
    confidence = Math.min(1, Math.max(0, toolInput.confidence));
    if (confidence !== toolInput.confidence) {
      warnings.push(`clamped confidence from ${toolInput.confidence} to ${confidence}`);
    }
  } else {
    warnings.push('confidence missing or non-numeric — defaulted to 0');
  }

  // reasoning
  let reasoning = '';
  if (typeof toolInput.reasoning === 'string') reasoning = toolInput.reasoning.trim();
  if (reasoning.length > MAX_REASONING_CHARS) {
    reasoning = `${reasoning.slice(0, MAX_REASONING_CHARS - 1)}…`;
    warnings.push(`truncated reasoning to ${MAX_REASONING_CHARS} chars`);
  }

  return {
    inferred,
    confidence,
    reasoning,
    classifier_version: CLASSIFIER_VERSION,
  };
}

/**
 * Classify a proof-of-work artifact into Atlas v0.4 role IDs.
 *
 * One Anthropic API call with strict tool_use. One retry if the first
 * response did not contain a valid tool block; hard error on second miss.
 * Hallucinated role IDs are filtered against the v0.4 list parsed from the
 * prompt file at module init.
 *
 * Warnings (dropped roles, clamped confidence, truncated reasoning) are
 * emitted via console.warn — the result is always returned, never thrown
 * for content reasons. Throws only on transport errors or hard tool miss.
 */
export async function classifyAtlasRoles(
  input: AtlasClassifierInput
): Promise<AtlasClassifierResult> {
  const userMessage = formatUserMessage(input);

  async function callOnce(): Promise<Anthropic.Messages.Message> {
    return client.messages.create({
      model: MODEL,
      max_tokens: MAX_TOKENS,
      system: SYSTEM_PROMPT,
      tools: [TOOL_DEFINITION],
      tool_choice: { type: 'tool', name: TOOL_NAME },
      messages: [{ role: 'user', content: userMessage }],
    });
  }

  let response = await callOnce();
  let toolBlock = findToolUseBlock(response.content);
  if (!toolBlock) {
    response = await callOnce();
    toolBlock = findToolUseBlock(response.content);
    if (!toolBlock) {
      throw new Error(
        `Atlas classifier: no ${TOOL_NAME} tool_use block in response after retry. stop_reason=${response.stop_reason}`
      );
    }
  }

  const warnings: string[] = [];
  const result = validateAndShape(toolBlock.input as ToolInput, warnings);
  for (const w of warnings) console.warn(`[atlas-classifier] ${w}`);
  return result;
}
